# Usa la versión LTS de Node.js para construir la aplicación
FROM node:lts-alpine as build

# Directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./
RUN npm install

# Copia el resto de los archivos
COPY . .

# Construye la aplicación
RUN npm run build

# Usa Nginx para servir la aplicación React construida
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Expone el puerto 80 de Nginx
EXPOSE 80

# Inicia Nginx al arrancar el contenedor
CMD ["nginx", "-g", "daemon off;"]
