name: Deploy Frontend TUZ 3190

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-tuz-3190:1.0.0 -f Dockerfile ./landing

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-tuz-3190:1.0.0

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/projects/tuz-landing-3190
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-tuz-3190:1.0.0
            docker compose up -d
